### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by orathaic** [jefferyto/gedit-necronomicon#1]
When following the installation instructions gedit (3.4.1) throws the following error: Could not find loader 'python3' for plugin 'necronomicon'

**Comment by jefferyto** [comment]
Hi, did you use `necronomicon.plugin.python2` (and renamed to `necronomicon.plugin`), instead of the existing `necronomicon.plugin` (which is for gedit >= 3.8)?

**Comment by orathaic** [comment]
Yep, just tried it again there. I'm not sure how to upgrade my version of gedit to 3.8 as i'm just using whatever is in the Ubuntu repositories... may look into that.

**Comment by jefferyto** [comment]
You shouldn't need to upgrade your gedit; the plugin should work with your version. (It will also be very difficult to upgrade gedit without updating your whole system.)

Can you open a terminal and copy-and-paste the output of this command:

```
cat ~/.local/share/gedit/plugins/necronomicon.plugin
```

Also, can you try completely restarting gedit before enabling the plugin? Please copy-and-paste the complete error message(s) you see.

**Comment by orathaic** [comment]
'cat ~/.local/share/gedit/plugins/necronomicon.plugin

# This file is for gedit 3.6 and earlier

[Plugin]
Loader=python
Module=necronomicon
IAge=3
Name=Necronomicon
Description=Reopen recently-closed files ("undo close tab")
Authors=Jeffery To jeffery.to@gmail.com
Copyright=Copyright © 2013 Jeffery To
Website=https://github.com/jefferyto/gedit-necronomicon
Version=0.1.0'

On 15 January 2014 10:11, Jeffery To notifications@github.com wrote:

> You shouldn't need to upgrade your gedit; the plugin should work with your
> version. (It will also be very difficult to upgrade gedit without updating
> your whole system.)
> 
> Can you open a terminal and copy-and-paste the output of this command:
> 
> cat ~/.local/share/gedit/plugins/necronomicon.plugin
> 
> Also, can you try completely restarting gedit before enabling the plugin?
> Please copy-and-paste the complete error message(s) you see.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jefferyto/gedit-necronomicon/issues/1#issuecomment-32348643
> .

## 
- Cian Ó Rathaille
- Gever Tulley on 5 dangerous things for
  kids...http://www.ted.com/talks/lang/eng/gever_tulley_on_5_dangerous_things_for_kids.html
- Ali Carr-Chellman: gaming to re-engage boys in
  learninghttp://www.ted.com/talks/ali_carr_chellman_gaming_to_re_engage_boys_in_learning.html

**Comment by jefferyto** [comment]
Perhaps you can check if you have another copy of the plugin installed somewhere? Possible locations:
-   /usr/share/gedit/plugins
-   /usr/lib/gedit/plugins
-   /usr/lib/[your_system_arch]/gedit/plugins, where [your_system_arch] is something like x86_64-linux-gnu

**Comment by jefferyto** [comment]
Closing due to lack of response / issue age.
